name: CI
on: [workflow_dispatch, push]

jobs:
  test:
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    name: Test
    runs-on: ${{ matrix.os }}
    environment: ${{ matrix.env_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Version
        shell: bash
        run: date --rfc-3339=date
