name: CI
on: workflow_dispatch

jobs:
  test-linux:
    strategy:
      matrix:
        env_name: [env0]
    name: Test Linux
    runs-on: ubuntu-latest
    environment: ${{ matrix.env_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - shell: pwsh
        run: |
          Write-Host ${{ vars.VERSION }}
          "{latest_version}={2000}" >> $env:GITHUB_ENV

      - shell: bash
        run: |
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repositories/${{ vars.GITHUB_REPOSITORY_ID }}/environments/${{ matrix.env_name }}/variables/VERSION \
            -f name='VERSION' \
            -f value='${{ env.latest_version }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - shell: pwsh
        run: |
          Write-Host ${{ vars.VERSION }}
