name: CI
on: workflow_dispatch

jobs:
  test-linux:
    name: Test Linux
    runs-on: ubuntu-latest
    environment: env0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - shell: pwsh
        run: |
          Write-Host $VERSION
