name: CI
on: [push, workflow_dispatch]

jobs:
  test-windows:
    name: Test Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - shell: pwsh
        run: New-Item -Force runtimes/win-x64/windows.txt

      - uses: actions/upload-artifact@v3
        with:
          name: windows
          path: runtimes/

  test-linux:
    name: Test Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - shell: pwsh
        run: |
          New-Item -Force runtimes/linux-x64/linux.txt
          New-Item -Force runtimes/linux-musl-x64/linux.txt

      - uses: actions/upload-artifact@v3
        with:
          name: linux
          path: runtimes/
