name: Set-Env

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      ProjectName: GitHubActionsTest

    steps:
    - name: Old
      run: |
         echo "::set-env name=Old::OldTest"

    - name: New
      shell: pwsh
      run: |
         echo "New=NewTest1" >> $GITHUB_ENV
         echo 'New=NewTest2' >> $GITHUB_ENV

    - name: Test
      run: |
         echo ${{ env.ProjectName }}
         echo $ProjectName
         echo ${{ env.Old }}
         echo $Old
         echo ${{ env.New }}
         echo $New