name: Set-Env

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      ProjectName: GitHubActionsTest

    steps:
    - name: Old
      run: |
         echo "::set-env name=Old::OldTest"
         echo "action_state=yellow" >> $GITHUB_ENV

    - name: New
      shell: pwsh
      run: |
         echo "New=NewTest1" >> $GITHUB_ENV
         echo 'New=NewTest2' >> $GITHUB_ENV

    - name: Test
      shell: pwsh
      run: |
         Write-Host ${{ env.ProjectName }}
         Write-Host ${{ env.Old }}
         Write-Host ${{ env.New }}
         Write-Host ${{ env.action_state }}