name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ProjectName: GitHubActionsTest

    steps:
    - name: Test
      shell: pwsh
      run: |
         echo "Test"
